version: '3.8'

services:
  deepgram-transcriber:
    build: .
    container_name: deepgram-transcriber
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3456/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s